export const testimonials = [
  {
    id: 1,
    name: "Stephen Addae",
    title: "Angular Developer at Basonit",
    image: "/assets/Stephen.jpg",
    content: "I had the pleasure of working with Nicholas Amissah on a project during our time at Microverse, an online software development course.\n\nNicholas is an exceptional front-end developer who consistently impressed me with his attention to detail and commitment to delivering high-quality work.\n\nI highly recommend Nicholas for any front-end development roles.\n\nHe would be a valuable asset to any team looking for a skilled and dedicated developer",
    date: "April 2023",
    category: "development",
  },
  {
    id: 2,
    name: "Badare Basem",
    title: "Freelancer at Upwork",
    image: "/assets/Basem.png",
    content: "I had the pleasure of working with Nicholas Amissah on a software development project, and I must say, he is an exceptional developer.\n\nNicholas is very considerate and willing to go above and beyond to ensure that everyone on the team is carried along.\n\nHe has a natural talent for leadership and is always willing to pull others along to ensure that the project is completed successfully.His ability to work well with others and his positive attitude made the project run smoothly.\n\nI would highly recommend Nicholas Amissah to any team looking for a talented and dedicated software developer.",
    date: "April 2034",
    category: "management",
  },
  {
    id: 3,
    name: "Kwasi Antwi Baayeh",
    title: "Freelance Web Developer",
    image: "/assets/Baayeh.jpg",
    content: "Nicholas is an excellent software developer whom I had the pleasure of studying with at Microverse.\n\nNicholas is a dedicated software developer with a passion for understanding how things work.\n\nHe has a positive attitude, a great sense of humour, and is always willing to collaborate with others to achieve a common goal.\n\nI highly recommend Nicholas for any software development position as he is a talented and dedicated professional who will undoubtedly make a valuable contribution to any organization lucky enough to have him on their team.",
    date: "April 2023",
    category: "design",
  },
  {
    id: 4,
    name: "MUSONG ERNEST AKEH",
    title: "Freelance Software Engineer",
    image: "/assets/Ernest.jpg",
    content: "Nicholas is a fantastic software engineer, and his detail-oriented approach made working with him a pleasure.\n\nDuring our time at Microverse, we extensively pair-programmed together, and I was constantly impressed by his work ethic.\n\nHe is also incredibly friendly and punctual, and by the end of our project, it felt like we had known each other for years.\n\nI wholeheartedly recommend him.",
    date: "April 2023",
    category: "development",
  },
];
