export const testimonials = [
  {
    id: 1,
    name: "Sarah Johnson",
    title: "Senior Developer at TechCorp",
    image: "https://randomuser.me/api/portraits/women/1.jpg",
    content: "Nicholas is an exceptional developer who consistently delivers high-quality work. His attention to detail and problem-solving skills are remarkable. It was a pleasure working with him on our latest project.",
    date: "June 2025",
    category: "development",
  },
  {
    id: 2,
    name: "Michael Chen",
    title: "Project Manager at InnovateSoft",
    image: "https://randomuser.me/api/portraits/men/2.jpg",
    content: "Working with Nicholas was a game-changer for our project. His technical expertise and ability to meet deadlines made him an invaluable team member. Highly recommended!",
    date: "May 2025",
    category: "management",
  },
  {
    id: 3,
    name: "Emma Williams",
    title: "UX Designer at DesignHub",
    image: "https://randomuser.me/api/portraits/women/3.jpg",
    content: "Nicholas has an incredible eye for detail and a deep understanding of user experience. His code is clean, well-documented, and always follows best practices.",
    date: "April 2025",
    category: "design",
  },
  {
    id: 4,
    name: "David Rodriguez",
    title: "Tech Lead at WebSolutions",
    image: "https://randomuser.me/api/portraits/men/4.jpg",
    content: "I've worked with many developers, but Nicholas stands out for his professionalism and technical skills. He's a great communicator and always delivers beyond expectations.",
    date: "March 2025",
    category: "development",
  },
  {
    id: 5,
    name: "Lisa Thompson",
    title: "Product Owner at AgileTeam",
    image: "https://randomuser.me/api/portraits/women/5.jpg",
    content: "Nicholas's ability to transform requirements into elegant solutions is impressive. He's proactive, detail-oriented, and a true professional in every sense.",
    date: "February 2025",
    category: "management",
  },
  {
    id: 6,
    name: "James Wilson",
    title: "CTO at StartupX",
    image: "https://randomuser.me/api/portraits/men/6.jpg",
    content: "Outstanding work ethic and technical expertise. Nicholas not only delivered excellent code but also provided valuable insights that improved our overall project architecture.",
    date: "January 2025",
    category: "development",
  }
];
